# Generated by Django 5.1 on 2024-08-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
